/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ToyChatCodes;

import static ToyChatCodes.ClientLogin.CurrentNickName;
import static ToyChatCodes.ClientLogin.TargetNickName;
import static ToyChatCodes.ClientLogin.sendPost;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;

/**
 *
 * @author xyh3984
 */
public class ClientChatWnd extends javax.swing.JFrame {

    /**
     * Creates new form ClientChatWnd
     */
    public ClientChatWnd() {
        initComponents();
        jChatTargetName.setText(ClientLogin.TargetNickName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jChatHistory = new javax.swing.JTextArea();
        jSndBtn = new javax.swing.JButton();
        jChatMessageField = new javax.swing.JTextField();
        jChatTargetName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jChatHistory.setEditable(false);
        jChatHistory.setColumns(20);
        jChatHistory.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jChatHistory.setRows(5);
        jScrollPane1.setViewportView(jChatHistory);

        jSndBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jSndBtn.setText("Send");
        jSndBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSndBtnActionPerformed(evt);
            }
        });

        jChatMessageField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jChatMessageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChatMessageFieldActionPerformed(evt);
            }
        });

        jChatTargetName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jChatTargetName.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jChatMessageField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSndBtn)))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jChatTargetName)
                .addGap(221, 221, 221))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jChatTargetName)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChatMessageField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSndBtn))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChatMessageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChatMessageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChatMessageFieldActionPerformed

    private void jSndBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSndBtnActionPerformed
        // TODO add your handling code here:
        String inputtext = jChatMessageField.getText();
        if (!inputtext.matches("") && inputtext != null) {
            try {
            List<NameValuePair> params = new ArrayList<NameValuePair>(4);
            params.add(new BasicNameValuePair("status", "chat"));
            params.add(new BasicNameValuePair("origin", CurrentNickName));
            params.add(new BasicNameValuePair("target", TargetNickName));
            params.add(new BasicNameValuePair("msg", inputtext));
            sendPost(params);
           
            } catch (Exception ex) {
                Logger.getLogger(ClientLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jSndBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientChatWnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientChatWnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientChatWnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientChatWnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientChatWnd().setVisible(true);
            }
        });
        
        new Runnable() {
            @Override
            public void run() {
                period_ask();
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(ClientChatWnd.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }.run();
    }
    
    public static void period_ask() {
         try {
            List<NameValuePair> params = new ArrayList<NameValuePair>(3);
            params.add(new BasicNameValuePair("status", "getmsg"));
            params.add(new BasicNameValuePair("origin", CurrentNickName));
            params.add(new BasicNameValuePair("target", TargetNickName));
            String returned_str = sendPost(params);
            System.out.println(returned_str);
           
            } catch (Exception ex) {
                Logger.getLogger(ClientLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jChatHistory;
    private javax.swing.JTextField jChatMessageField;
    private javax.swing.JLabel jChatTargetName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSndBtn;
    // End of variables declaration//GEN-END:variables
}
